### ISSUE TITLE
pulp browserify fails

### ISSUE THREAD

**Issue by delanoe** [slamdata/purescript-echarts#27]
npm run build 
build succeeds but
==>

* Browserifying...
events.js:141
      throw er; // Unhandled 'error' event

Error: Cannot find module 'echarts' from '/home/user/purescript/purescript-echarts/output/ECharts.Chart'
    at /usr/local/lib/node_modules/pulp/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/pulp/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/pulp/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/pulp/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/pulp/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/pulp/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! purescript-echarts@ build: `pulp browserify --include example/src --to public/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR!     pulp browserify --include example/src --to public/build.js
npm ERR! System Linux 4.8.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! cwd /home/user/purescript-echarts
npm ERR! node -v v4.7.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

Do you know how to fix this please ?

**Comment by delanoe** [comment]
Solution:
git clone 
cd purescript-echarts
npm install
npm run build
npm run serve
And it works!

Thanks for these bindings.
